# Generated by Django 5.0.2 on 2024-02-16 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('picture', models.ImageField(max_length=500, upload_to='party_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_name', models.CharField(max_length=100)),
                ('voter_email', models.EmailField(max_length=254, unique=True)),
                ('voter_ip', models.CharField(max_length=15, unique=True)),
                ('voted_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.party')),
            ],
        ),
    ]
