# Generated by Django 5.0.2 on 2024-02-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='code',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='party',
            name='picture',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
